Update

diff --git a/openldap/entry b/openldap/entry
--- a/openldap/entry
+++ b/openldap/entry
@@ -1,23 +1,100 @@
 #!/bin/sh
 
+# When not limiting the open file descritors limit, the memory consumption of
+# slapd is absurdly high. See https://github.com/docker/docker/issues/8231
+ulimit -n 8192
+
+
 set -e
 
-# Add ldap as command if needed
-if [ "${1:0:1}" = '-' ]; then
-	set -- $OLDAP_USER "$@"
+SLAPD_FORCE_RECONFIGURE="${SLAPD_FORCE_RECONFIGURE:-false}"
+
+first_run=true
+
+if [[ -f "$OLDAP_DATA/etc/openldap/DB_CONFIG" ]]; then
+    first_run=false
+else
+    mv /tmp/* $OLDAP_DATA/
 fi
 
-# Drop root privileges if we are running ldap
-# allow the container to be started with `--user`
-if [ "$1" = '/usr/local/libexec/slapd' -a "$(id -u)" = '0' ]; then
-  mkdir -p "$OLDAP_DATA"
-	if [ ! -d $OLDAP_DATA/etc ]; then
-		mv /tmp/* $OLDAP_DATA/
-	fi
-	chmod 700 "$OLDAP_DATA"
-	chown -R $OLDAP_GROUP:$OLDAP_USER $OLDAP_DATA
+if [[ ! -d $OLDAP_DATA/etc/openldap/slapd.d || "$SLAPD_FORCE_RECONFIGURE" == "true" ]]; then
+
+    if [[ -z "$SLAPD_PASSWORD" ]]; then
+        echo -n >&2 "Error: Container not configured and SLAPD_PASSWORD not set. "
+        echo >&2 "Did you forget to add -e SLAPD_PASSWORD=... ?"
+        exit 1
+    fi
+
+    if [[ -z "$SLAPD_DOMAIN" ]]; then
+        echo -n >&2 "Error: Container not configured and SLAPD_DOMAIN not set. "
+        echo >&2 "Did you forget to add -e SLAPD_DOMAIN=... ?"
+        exit 1
+    fi
+
+    SLAPD_ORGANIZATION="${SLAPD_ORGANIZATION:-${SLAPD_DOMAIN}}"
+
+    dc_string=""
+
+    IFS="."; declare -a dc_parts=($SLAPD_DOMAIN); unset IFS
+
+    for dc_part in "${dc_parts[@]}"; do
+        dc_string="$dc_string,dc=$dc_part"
+    done
+
+    base_string="BASE ${dc_string:1}"
+
+    sed -i "s/^#BASE.*/${base_string}/g" $OLDAP_DATA/etc/openldap/ldap.conf
+
+    if [[ -n "$SLAPD_CONFIG_PASSWORD" ]]; then
+        password_hash=`slappasswd -s "$SLAPD_CONFIG_PASSWORD"`
+
+        sed_safe_password_hash=${password_hash//\//\\\/}
+
+        slapcat -n0 -F $OLDAP_DATA/etc/openldap/slapd.d -l /tmp/config.ldif
+        sed -i "s/\(olcRootDN: cn=admin,cn=config\)/\1\nolcRootPW: ${sed_safe_password_hash}/g" /tmp/config.ldif
+        rm -rf $OLDAP_DATA/etc/openldap/slapd.d/*
+        slapadd -n0 -F $OLDAP_DATA/etc/openldap/slapd.d -l /tmp/config.ldif
+        rm -f /tmp/config.ldif
+    fi
+
+    if [[ -n "$SLAPD_ADDITIONAL_SCHEMAS" ]]; then
+        IFS=","; declare -a schemas=($SLAPD_ADDITIONAL_SCHEMAS); unset IFS
+
+        for schema in "${schemas[@]}"; do
+            slapadd -n0 -F $OLDAP_DATA/etc/openldap/slapd.d -l "$OLDAP_DATA/etc/openldap/schema/${schema}.ldif"
+        done
+    fi
+
+    if [[ -n "$SLAPD_ADDITIONAL_MODULES" ]]; then
+        IFS=","; declare -a modules=($SLAPD_ADDITIONAL_MODULES); unset IFS
+
+        for module in "${modules[@]}"; do
+             module_file="$OLDAP_DATA/etc/openldap/modules/${module}.ldif"
+
+             if [ "$module" == 'ppolicy' ]; then
+                 SLAPD_PPOLICY_DN_PREFIX="${SLAPD_PPOLICY_DN_PREFIX:-cn=default,ou=policies}"
+
+                 sed -i "s/\(olcPPolicyDefault: \)PPOLICY_DN/\1${SLAPD_PPOLICY_DN_PREFIX}$dc_string/g" $module_file
+             fi
+
+             slapadd -n0 -F $OLDAP_DATA/etc/openldap/slapd.d -l "$module_file"
+        done
+    fi
+else
+    slapd_configs_in_env=`env | grep 'SLAPD_'`
+
+    if [ -n "${slapd_configs_in_env:+x}" ]; then
+        echo "Info: Container already configured, therefore ignoring SLAPD_xxx environment variables and preseed files"
+    fi
 fi
-# As argument is not related to ldap,
-# then assume that user wants to run his own process,
-# for example a `bash` shell to explore this image
+
+if [[ "$first_run" == "true" ]]; then
+    if [[ -d "$OLDAP_DATA/etc/openldap/prepopulate" ]]; then
+        for file in `ls $OLDAP_DATA/etc/openldap/prepopulate/*.ldif`; do
+            slapadd -F $OLDAP_DATA/etc/openldap/slapd.d -l "$file"
+        done
+    fi
+fi
+
+chown -R $OLDAP_GROUP:$OLDAP_USER $OLDAP_DATA
 exec "$@"
