Alpine:Postgres 9.6.2 build Okey

diff --git a/postgres/entry b/postgres/entry
--- a/postgres/entry
+++ b/postgres/entry
@@ -1,82 +1,141 @@
-#!/bin/sh
+#!/bin/bash
 
 set -e
 
+# usage: file_env VAR [DEFAULT]
+#    ie: file_env 'XYZ_DB_PASSWORD' 'example'
+# (will allow for "$XYZ_DB_PASSWORD_FILE" to fill in the value of
+#  "$XYZ_DB_PASSWORD" from a file, especially for Docker's secrets feature)
+file_env() {
+	local var="$1"
+	local fileVar="${var}_FILE"
+	local def="${2:-}"
+	if [ "${!var:-}" ] && [ "${!fileVar:-}" ]; then
+		echo >&2 "error: both $var and $fileVar are set (but are exclusive)"
+		exit 1
+	fi
+	local val="$def"
+	if [ "${!var:-}" ]; then
+		val="${!var}"
+	elif [ "${!fileVar:-}" ]; then
+		val="$(< "${!fileVar}")"
+	fi
+	export "$var"="$val"
+	unset "$fileVar"
+}
+
 if [ "${1:0:1}" = '-' ]; then
-	set -- $PG_USER "$@"
+	set -- ${PG_USER} "$@"
 fi
 
-mkdir -p $PG_DATA
-
-# Init
-if [ ! -d $PG_DATA/data ]; then
+if [ ! -d ${PG_DATA}/data ]; then
 	cp -r /tmp/* $PG_DATA/
 	mkdir -p $PG_DATA/log
-  mv /etc/postgresql  $PG_DATA/
-	ln -s $PG_DATA/postgresql /etc/postgresql
 	chmod 700 $PG_DATA
-  chown -R $PG_GROUP:$PG_USER $PG_HOME
-	chown -R $PG_GROUP:$PG_USER $PG_DATA
+fi
 
-	if [ "$PGPASSWORD" ]; then
-		pass="PASSWORD '$PGPASSWORD'"
-		authMethod=md5
-	else
-		cat >&2 <<-'EOWARN'
+chown -R $PG_GROUP:$PG_USER $PG_HOME
+chown -R $PG_GROUP:$PG_USER $PG_DATA
+
+# allow the container to be started with `--user`
+if [ "$1" = 'postgres' ] && [ "$(id -u)" = '0' ]; then
+	mkdir -p "$PGDATA"
+	chown -R $PG_USER "$PGDATA"
+	chmod 700 "$PGDATA"
+
+	mkdir -p /var/run/postgresql
+	chown -R $PG_USER /var/run/postgresql
+	chmod g+s /var/run/postgresql
+
+	exec su-exec $PG_USER "$BASH_SOURCE" "$@"
+fi
+
+if [ "$1" = 'postgres' ]; then
+	mkdir -p "$PGDATA"
+	chown -R "$(id -u)" "$PGDATA" 2>/dev/null || :
+	chmod 700 "$PGDATA" 2>/dev/null || :
+
+    # look specifically for PG_VERSION, as it is expected in the DB dir
+	if [ ! -s "$PGDATA/PG_VERSION" ]; then
+		file_env 'POSTGRES_INITDB_ARGS'
+		eval "initdb --username=postgres $POSTGRES_INITDB_ARGS"
+
+		# check password first so we can output the warning before postgres
+		# messes it up
+		file_env 'PGPASSWORD'
+		if [ "$PGPASSWORD" ]; then
+			pass="PASSWORD '$PGPASSWORD'"
+			authMethod=md5
+		else
+			# The - option suppresses leading tabs but *not* spaces. :)
+			cat >&2 <<-'EOWARN'
 			****************************************************
-			WARNING: No password has been set for the database.
-							 This will allow anyone with access to the
-							 Postgres port to access your database. In
-							 Docker's default configuration, this is
-							 effectively any other container on the same
-							 system.
-							 Use "-e POSTGRES_PASSWORD=password" to set
-							 it in "docker run".
-			****************************************************
-		EOWARN
+				WARNING: No password has been set for the database.
+				         This will allow anyone with access to the
+				         Postgres port to access your database. In
+				         Docker's default configuration, this is
+				         effectively any other container on the same
+				         system.
+				         Use "-e PGPASSWORD=password" to set
+				         it in "docker run".
+				****************************************************
+			EOWARN
 
-		pass=
-		authMethod=trust
-	fi
+			pass=
+			authMethod=trust
+		fi
 
-	{ echo; echo "host all all 0.0.0.0/0 $authMethod"; } >> "$PGDATA/pg_hba.conf"
+		{ echo; echo "host all all all $authMethod"; } | tee -a "$PGDATA/pg_hba.conf" > /dev/null
 
-	gosu $PG_USER pg_ctl -D $PGDATA \
-	  -l $PG_DATA/log/logfile \
-		-o "-c listen_addresses='localhost'" \
-		-w start
+		# internal start of server in order to allow set-up using psql-client		
+		# does not listen on external TCP/IP and waits until start finishes
+		PG_USER="${PG_USER:-postgres}" \
+		pg_ctl -D "$PGDATA" \
+			-o "-c listen_addresses='localhost'" \
+			-w start
 
-	if [ "$PGDATABASE" != 'postgres' ]; then
-	  psql -v ON_ERROR_STOP=1 --username $PGUSER <<-EOSQL
-		  CREATE DATABASE "$PGDATABASE" ;
+		file_env 'PGUSER' 'postgres'
+		file_env 'PGDATABASE' "$PGUSER"
+
+		psql=( psql -v ON_ERROR_STOP=1 )
+
+		if [ "$PGDATABASE" != 'postgres' ]; then
+			"${psql[@]}" --username postgres <<-EOSQL
+				CREATE DATABASE "$PGDATABASE" ;
+			EOSQL
+			echo
+		fi
+
+		if [ "$PGUSER" = 'postgres' ]; then
+			op='ALTER'
+		else
+			op='CREATE'
+		fi
+		"${psql[@]}" --username postgres <<-EOSQL
+			$op USER "$PGUSER" WITH SUPERUSER $pass ;
 		EOSQL
 		echo
+
+		psql+=( --username "$PGUSER" --dbname "$PGDATABASE" )
+
+		echo
+		for f in /docker-entrypoint-initdb.d/*; do
+			case "$f" in
+				*.sh)     echo "$0: running $f"; . "$f" ;;
+				*.sql)    echo "$0: running $f"; "${psql[@]}" -f "$f"; echo ;;
+				*.sql.gz) echo "$0: running $f"; gunzip -c "$f" | "${psql[@]}"; echo ;;
+				*)        echo "$0: ignoring $f" ;;
+			esac
+			echo
+		done
+
+		PG_USER="${PG_USER:-postgres}" \
+		pg_ctl -D "$PGDATA" -m fast -w stop
+
+		echo
+		echo 'PostgreSQL init process complete; ready for start up.'
+		echo
 	fi
-
-	if [ "$PGUSER" = 'postgres' ]; then
-	  op='ALTER'
-	else
-		op='CREATE'
-	fi
-
-	psql -v ON_ERROR_STOP=1 --username $PGUSER <<-EOSQL
-		$op USER "$PGUSER" WITH SUPERUSER $pass ;
-	EOSQL
-	echo
-	# psql -v ON_ERROR_STOP=1 --username $PGUSER --dbname $PGDATABASE
-	# echo
-	gosu $PG_USER pg_ctl -D "$PGDATA" \
-	  -m fast \
-		-w stop
-
-	echo
-	echo 'PostgreSQL init process complete; ready for start up.'
-	echo
 fi
 
-# Run
-if [ "$1" = 'postgres' ]; then
-	exec gosu $PG_USER "$@"
-else
-  exec "$@"
-fi
+exec "$@"
